[package]
name = "mcatool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="3.0.14", features=["cargo"]}
flate2 = { version = "1.0.22", features = ["zlib"], default-features = false }
